### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by magixyu** [sanyu1225/vue-cli-plugin-chrome-extension-cli#10]
When I follow the instruction to create the extension app, the below error occurred:
```PS D:\myproj\autorobot> vue add chrome-extension-cli -r https://repo.lab.pl.alcatel-lucent.com/api/npm/npm-remote
 WARN  There are uncommitted changes in the current repository, it's recommended to commit or stash them first.
? Still proceed? Yes

📦  Installing vue-cli-plugin-chrome-extension-cli...

yarn add v1.22.11
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved 1 new dependency.
info Direct dependencies
└─ vue-cli-plugin-chrome-extension-cli@1.0.8
info All dependencies
└─ vue-cli-plugin-chrome-extension-cli@1.0.8
Done in 15.09s.
✔  Successfully installed plugin: vue-cli-plugin-chrome-extension-cli


🚀  Invoking generator for vue-cli-plugin-chrome-extension-cli...
 ERROR  TypeError: Cannot read property 'forEach' of undefined
TypeError: Cannot read property 'forEach' of undefined
    at module.exports (D:\myproj\autorobot\node_modules\vue-cli-plugin-chrome-extension-cli\generator\index.js:24:14)
    at Generator.initPlugins (C:\Users\tristany\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:150:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Generator.generate (C:\Users\tristany\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:168:5)
    at async runGenerator (C:\Users\tristany\AppData\Roaming\npm\node_modules\@vue\cli\lib\invoke.js:111:3)
    at async invoke (C:\Users\tristany\AppData\Roaming\npm\node_modules\@vue\cli\lib\invoke.js:92:3)
```

**Comment by sanyu1225** [comment]
sorry, I can’t reproduce, please provide the os system, node.js version or yarn version, vue-cli version, and the version that created vue

**Comment by magixyu** [comment]
I tried another laptop. The issue is gone. But on my current laptop, the issue stays.
Here is the information(all commands are executed in powershell 7.2)
```
PS D:\myproj\autorobot> npm version
{
  autorobot: '0.1.0',
  npm: '6.14.14',
  ares: '1.17.2',
  brotli: '1.0.9',
  cldr: '39.0',
  icu: '69.1',
  llhttp: '2.1.3',
  modules: '83',
  napi: '8',
  nghttp2: '1.42.0',
  node: '14.17.5',
  openssl: '1.1.1k',
  tz: '2021a',
  unicode: '13.0',
  uv: '1.41.0',
  v8: '8.4.371.23-node.76',
  zlib: '1.2.11'
}
PS D:\myproj\autorobot> yarn --version
1.22.17
PS D:\myproj\autorobot> node -v
v14.17.5
PS D:\myproj\autorobot> vue --version
@vue/cli 4.5.15
```

**Comment by magixyu** [comment]
Add OS information:
Microsoft Windows [Version 10.0.19042.1288]

**Comment by magixyu** [comment]
I clean my cache, remove all lock files. Then, the issue disappeared.

Strange for a while

Thanks @sanyu1225 for helping on this issue over night.
