### ISSUE TITLE
[BUG] Typescript support ?

### ISSUE THREAD

**Issue by Mikaleb** [sanyu1225/vue-cli-plugin-chrome-extension-cli#27]
**Describe the bug**

**To Reproduce**

1. Use Vue cli create project 
```
Vue CLI v5.0.1
? Please pick a preset: Manually select features
? Check the features needed for your project: Babel, TS, CSS Pre-processors, Linter
? Choose a version of Vue.js that you want to start the project with 3.x
? Use class-style component syntax? No
? Use Babel alongside TypeScript (required for modern mode, auto-detected polyfills, transpiling JSX)? Yes
? Pick a CSS pre-processor (PostCSS, Autoprefixer and CSS Modules are supported by default): Sass/SCSS (with dart-sass)
? Pick a linter / formatter config: Prettier
? Pick additional lint features: Lint on save
? Where do you prefer placing config for Babel, ESLint, etc.? In dedicated config files
? Save this as a preset for future projects? No
```

2. Install chrome-extension-cli Plugin 
```
? Name of the Chrome Extension? chrome-extension-name
? Description for the Chrome Extension? chrome extension
? Version for the Chrome Extension? 0.0.1
? manifest_version for the Chrome Extension? 3
? delete Initial file? (src/main.js src/components public/index.html public/favicon) Yes
? Please select the required components : background, popup, content
```
5. See error ```something error...```

**Expected behavior**

**Screenshots**

***please complete the following information:***
 - Node Version: [16.14.0]
 - OS: [Mac OS Big Sur]
 - Vue Cli Version [5.0.1]

**Additional context**

**Comment by sanyu1225** [comment]
<img width="706" alt="image" src="https://user-images.githubusercontent.com/36758238/159343909-485a4bdf-75fc-48bd-a723-f4b673a6a53d.png">
Can you describe the problem you encountered?
I just tested it and it was fine

**Comment by Mikaleb** [comment]
Woops my bad I didn't saw I sent the PR, here are the missing infos : 

New project : 

```
? Please pick a preset: Manually select features
? Check the features needed for your project: Choose Vue version, Babel, TS, Router, Vuex, Linter, Unit, E2E
? Choose a version of Vue.js that you want to start the project with 2.x
? Use class-style component syntax? No
? Use Babel alongside TypeScript (required for modern mode, auto-detected polyfills, transpiling JSX)? Yes
? Use history mode for router? (Requires proper server setup for index fallback in production) Yes
? Pick a linter / formatter config: Basic
? Pick additional lint features: Lint on save
? Pick a unit testing solution: Jest
? Pick an E2E testing solution: Cypress
? Where do you prefer placing config for Babel, ESLint, etc.? In dedicated config files
? Save this as a preset for future projects? No
```

Adding CLI Chrome : 

```
✔  Successfully installed plugin: vue-cli-plugin-chrome-extension-cli

? Name of the Chrome Extension? chrome-extension-name
? Description for the Chrome Extension? chrome extension
? Version for the Chrome Extension? 0.0.1
? manifest_version for the Chrome Extension? 2
? delete Initial file? (src/main.js src/components public/index.html public/favicon) Yes
? Please select the required components : background, popup, content, options, devtools

🚀  Invoking generator for vue-cli-plugin-chrome-extension-cli...
📦  Installing additional dependencies...


added 4 packages, and audited 1794 packages in 2s

107 packages are looking for funding
  run `npm fund` for details

95 vulnerabilities (29 moderate, 66 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
⠋  Running completion hooks...warning: Missing return type on function (@typescript-eslint/explicit-module-boundary-types) at src/view/devtools.vue:10:3:
   8 | export default {
   9 |   name: 'devtoolsView',
> 10 |   data () {
     |   ^
  11 |     return {
  12 |       msg: 'devdools'
  13 |     }


warning: Missing return type on function (@typescript-eslint/explicit-module-boundary-types) at src/view/options.vue:10:3:
   8 | export default {
   9 |   name: 'optionsView',
> 10 |   data () {
     |   ^
  11 |     return {
  12 |       msg: 'options'
  13 |     }


warning: Missing return type on function (@typescript-eslint/explicit-module-boundary-types) at src/view/popup.vue:10:3:
   8 | export default {
   9 |   name: 'popupView',
> 10 |   data () {
     |   ^
  11 |     return {
  12 |       msg: 'popup'
  13 |     }


error: Require statement not part of import statement (@typescript-eslint/no-var-requires) at vue.config.js:1:14:
> 1 | const path = require('path')
    |              ^
  2 | const fs = require('fs')
  3 |
  4 | // Generate pages object


error: Require statement not part of import statement (@typescript-eslint/no-var-requires) at vue.config.js:2:12:
  1 | const path = require('path')
> 2 | const fs = require('fs')
    |            ^
  3 |
  4 | // Generate pages object
  5 | const pages = {}


error: Require statement not part of import statement (@typescript-eslint/no-var-requires) at vue.config.js:33:31:
  31 |   filenameHashing: false,
  32 |   chainWebpack: (config) => {
> 33 |     config.plugin('copy').use(require('copy-webpack-plugin'), [
     |                               ^
  34 |       {
  35 |         patterns: [
  36 |           {


3 errors and 3 warnings found.
```

**Comment by sanyu1225** [comment]
it's eslint rule error, not typescript support error
