### ISSUE TITLE
[BUG] New setup CopyPlugin

### ISSUE THREAD

**Issue by Mikaleb** [sanyu1225/vue-cli-plugin-chrome-extension-cli#28]
**Describe the bug**

**To Reproduce**

```

npm run build-watch 

> vue-cli-service  --env.NODE_ENV=development build-watch --mode development


⠋  Building for development.../home/mikaleb/Companies/Datananas/code/connect/test-ext/node_modules/copy-webpack-plugin/node_modules/schema-utils/src/validateOptions.js:32
    throw new ValidationError(ajv.errors, name);
          ^

ValidationError: CopyPlugin Invalid Options

options should be array

    at validateOptions (/home/mikaleb/Companies/Datananas/code/connect/test-ext/node_modules/copy-webpack-plugin/node_modules/schema-utils/src/validateOptions.js:32:11)
    at new CopyPlugin (/home/mikaleb/Companies/Datananas/code/connect/test-ext/node_modules/copy-webpack-plugin/dist/index.js:26:30)
    at /home/mikaleb/Companies/Datananas/code/connect/test-ext/node_modules/webpack-chain/src/Plugin.js:14:18
    at Object.toConfig (/home/mikaleb/Companies/Datananas/code/connect/test-ext/node_modules/webpack-chain/src/Plugin.js:78:22)
    at /home/mikaleb/Companies/Datananas/code/connect/test-ext/node_modules/webpack-chain/src/Config.js:129:63
    at Array.map (<anonymous>)
    at module.exports.toConfig (/home/mikaleb/Companies/Datananas/code/connect/test-ext/node_modules/webpack-chain/src/Config.js:129:40)
    at Service.resolveWebpackConfig (/home/mikaleb/Companies/Datananas/code/connect/test-ext/node_modules/@vue/cli-service/lib/Service.js:245:34)
    at PluginAPI.resolveWebpackConfig (/home/mikaleb/Companies/Datananas/code/connect/test-ext/node_modules/@vue/cli-service/lib/PluginAPI.js:132:25)
    at module.exports (/home/mikaleb/Companies/Datananas/code/connect/test-ext/node_modules/@vue/cli-service/lib/commands/build/resolveAppConfig.js:46:14)
    at build (/home/mikaleb/Companies/Datananas/code/connect/test-ext/node_modules/@vue/cli-service/lib/commands/build/index.js:147:50)
    at /home/mikaleb/Companies/Datananas/code/connect/test-ext/node_modules/@vue/cli-service/lib/commands/build/index.js:89:13
    at Service.run (/home/mikaleb/Companies/Datananas/code/connect/test-ext/node_modules/@vue/cli-service/lib/Service.js:230:12)
    at /home/mikaleb/Companies/Datananas/code/connect/test-ext/node_modules/vue-cli-plugin-chrome-extension-cli/index.js:11:17
    at Service.run (/home/mikaleb/Companies/Datananas/code/connect/test-ext/node_modules/@vue/cli-service/lib/Service.js:230:12)
    at Object.<anonymous> (/home/mikaleb/Companies/Datananas/code/connect/test-ext/node_modules/@vue/cli-service/bin/vue-cli-service.js:36:9) {
  errors: [
    {
      keyword: 'type',
      dataPath: '',
      schemaPath: '#/type',
      params: { type: 'array' },
      message: 'should be array'
    }
  ]
}

```

1. Use Vue cli create project 
```
Vue CLI v5.0.1
? Please pick a preset: Manually select features
? Check the features needed for your project: Choose Vue version, Babel, Router, Vuex, CSS Pre-processors, Linter, Unit, E2E
? Choose a version of Vue.js that you want to start the project with 2.x
? Use history mode for router? (Requires proper server setup for index fallback in production) Yes
? Pick a CSS pre-processor (PostCSS, Autoprefixer and CSS Modules are supported by default): Sass/SCSS (with dart-sass)
? Pick a linter / formatter config: Basic
? Pick additional lint features: Lint on save
? Pick a unit testing solution: Jest
? Pick an E2E testing solution: Cypress
? Where do you prefer placing config for Babel, ESLint, etc.? In dedicated config files
? Save this as a preset for future projects? No
```

2. Install chrome-extension-cli Plugin 
```
✔  Successfully installed plugin: vue-cli-plugin-chrome-extension-cli

? Name of the Chrome Extension? chrome-extension-name
? Description for the Chrome Extension? chrome extension
? Version for the Chrome Extension? 0.0.1
? manifest_version for the Chrome Extension? 2
? delete Initial file? (src/main.js src/components public/index.html public/favicon) Yes
? Please select the required components : background, popup, content
```
5. See error ```something error...```

**Expected behavior**

**Screenshots**

***please complete the following information:***
 - Node Version: 16.11.0
 - OS: Ubuntu 20.04
 - Vue Cli Version @vue/cli 4.5.13

**Additional context**

**Comment by sanyu1225** [comment]
upgrade your vue-cli version , i will add notice in readme.md

**Comment by Mikaleb** [comment]
@sanyu1225 that's the highest version on Ubuntu rn

**Comment by Vidhyanandcs** [comment]
I upgraded the vue-cli version. But the error persist.
Currently using `@vue/cli 5.0.4`
![Capture](https://user-images.githubusercontent.com/11901913/171133303-73eaeaab-27ca-413c-9201-f7c7a19b55e7.PNG)

**Comment by Vidhyanandcs** [comment]
I think with manifest 3 there is a problem in using `npm run build-watch`. is there an alternative

**Comment by Vidhyanandcs** [comment]
Update: i updated the vue-cli and then recreated the project. Then it worked.
