### ISSUE TITLE
TypeError: api.afterInvoke is not a function

### ISSUE THREAD

**Issue by hashpoker** [sanyu1225/vue-cli-plugin-chrome-extension-cli#35]
/node_modules/vue-cli-plugin-chrome-extension-cli/generator/index.js:40
  api.afterInvoke(() => {
      ^

TypeError: api.afterInvoke is not a function
    at module.exports (/Users/wzy/easymoney/node_modules/vue-cli-plugin-chrome-extension-cli/generator/index.js:40:7)
    at /usr/local/lib/node_modules/@vue/cli/lib/Generator.js:103:7
    at Array.forEach (<anonymous>)
    at new Generator (/usr/local/lib/node_modules/@vue/cli/lib/Generator.js:101:13)
    at runGenerator (/usr/local/lib/node_modules/@vue/cli/lib/invoke.js:123:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async invoke (/usr/local/lib/node_modules/@vue/cli/lib/invoke.js:117:3)

**Comment by sanyu1225** [comment]
@hashpoker 
 can you provide your node.js , vue-cli  version  and os ?

**Comment by sanyu1225** [comment]
The test is normal, close the issue
